version: 2
jobs:
  build_docker_image:
    working_directory: /tmp/build
    docker:
      - image: circleci/node:8
    steps:
      - checkout
      - setup_remote_docker
      - run:
          name: build
          command: docker build -t spareroom/gocd-monitor:$CIRCLE_BUILD_NUM -t spareroom/gocd-monitor:latest .
      - run:
          name: push
          command: |
            docker -v
            docker login --username $DOCKER_USER --password $DOCKER_PASS
            docker push spareroom/gocd-monitor:$CIRCLE_BUILD_NUM
            docker push spareroom/gocd-monitor:latest
workflows:
  version: 2
  build:
    jobs:
      - build_docker_image:
          context: org-global
